name: btrecorder
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  camera: ^0.10.5+8
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.7
  get: ^4.6.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
